### ISSUE TITLE
Run on already uploaded images?

### ISSUE THREAD

**Issue by dexteredwards** [iandoe/kirby-dominant-color#2]
Wondering if it would it be possible to run this function retrospectively on already uploaded images?

In other words, rather than re-uploading everything and having the function run on the images as they are uploaded – would it be possible to pick out the dominant color for all images at once? 

Loving this plugin thank you!

**Comment by iandoe** [comment]
Hey @dexteredwards, sorry, i do not have time to maintain this at the moment, but happy to review any PR that would provide this functionnality.

Regards
